# Generated by Django 3.1.5 on 2021-01-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomCode', models.CharField(default='', max_length=20)),
                ('contestantsCount', models.IntegerField(default=0)),
                ('submissions', models.TextField(default='', max_length=10000)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetroyale.room')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('budgetPlan', models.TextField(default='')),
                ('BudgetCateg', models.CharField(default='', max_length=255)),
                ('yesVotes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgetroyale.user')),
            ],
        ),
    ]
